USE [master]
CREATE LOGIN [User2_k] WITH PASSWORD=N'changeme', 
DEFAULT_DATABASE=[master], DEFAULT_LANGUAGE=[русский], 
CHECK_EXPIRATION=ON, CHECK_POLICY=ON
USE [Base_k]
CREATE USER [User2_k] FOR LOGIN [User2_k] 
